-- FUNCTION (부서 번호를 입력하면 부서명을 리턴해주는 함수를 만들기)
-- 만약 없는 부서 번호이면 해당부서없음 리턴
CREATE OR REPLACE FUNCTION GET_DEPARTMENT_NAME_FUNC(VDEPARTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE) 
RETURN VARCHAR2
IS
    VDEPARTMENT_NAME VARCHAR2(100); 
    VCOUNT NUMBER := 0; 
BEGIN
    -- 해당부서의 카운트를 체크
    SELECT COUNT(*)INTO VCOUNT FROM EMPLOYEES WHERE DEPARTMENT_ID = VDEPARTMENT_ID; 

    IF(VCOUNT = 0)THEN
        VDEPARTMENT_NAME := '해당부서없음';
    ELSE
        SELECT DEPARTMENT_NAME INTO VDEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID = VDEPARTMENT_ID;
    END IF; 
    RETURN VDEPARTMENT_NAME;
END;
/
--함수를 이용해서 부서번호를 매개변수 등록하고 부서명 구하는 기능 사용
select * from employees;
select FIRST_NAME,SALARY, DEPARTMENT_ID,GET_DEPARTMENT_NAME_FUNC
(DEPARTMENT_ID) AS "DEPARTMENT_NAME" from EMPLOYEES WHERE FIRST_NAME = 'Lex';

VARIABLE VNAME varchar2;
EXECUTE :VNAME := GET_DEPARTMENT_NAME_FUNC(90);
print VNAME;
